[Эйдлин Иван] Модуль7-Задача5-Мосты
ozmld/algorithms-mipt pull request #26
Opened 2023-04-10 17:38 UTC by ozmld

1) https://contest.yandex.ru/contest/47173/run-report/83804037/
2) https://contest.yandex.ru/contest/47173/run-report/86358331/

2023-04-23 15:50 UTC, vels3113 requested changes

2023-04-23 15:50 UTC, vels3113 commented on module7-taskE.cpp
> +    if (edges_.count({v, u}) == 0) {
не понимаю, зачем логика в методе добавления ребра

2023-04-23 15:50 UTC, vels3113 commented on module7-taskE.cpp
> +  void AddEdge(unsigned short v, unsigned short u, size_t num) {
строго говоря, ребра безопаснее нумеровать счетчиком внутри класса (потому что неясно, что будет, если подать 2 ребра с одинаковым num).  Однако в этой задаче num по сути не используется

2023-04-24 16:16 UTC, ibulgakov requested changes

2023-04-24 16:16 UTC, ibulgakov commented on module7-taskE.cpp
> +  explicit Graph() : graph_({}) {}
пустой конструктор не нужен

2023-04-24 16:16 UTC, ibulgakov commented on module7-taskE.cpp
> +
лишняя пустая строка

2023-04-24 16:16 UTC, ibulgakov commented on module7-taskE.cpp
> +
лишняя пустая строка

2023-04-24 16:40 UTC, ibulgakov approved these changes

2023-04-24 16:41 UTC, merged